force-app/main/default/objects/Company__c/Company__c.object-meta.xml
<CustomObject>
    <label>Company</label>
    <nameField>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Company</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Competency__c/Competency__c.object-meta.xml
<CustomObject>
    <label>Competency</label>
    <nameField>
        <label>Competency Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Competency</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Competency__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <label>Company</label>
    <referenceTo>Company__c</referenceTo>
    <relationshipLabel>Competency</relationshipLabel>
    <relationshipName>Competency</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Module__c/Module__c.object-meta.xml
<CustomObject>
    <label>Module</label>
    <nameField>
        <label>Module Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Modules</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Module__c/fields/Projects__c.field-meta.xml
<CustomField>
    <fullName>Projects__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Modules</relationshipLabel>
    <relationshipName>Modules</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <label>Company</label>
    <referenceTo>Company__c</referenceTo>
    <relationshipLabel>Project</relationshipLabel>
    <relationshipName>Project</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>Start date for project</description>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Project_Competency__c/Project_Competency__c.object-meta.xml
<CustomObject>
    <label>Project Competency</label>
    <nameField>
        <label>Competency Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Competency</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Competency__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Project Competency</relationshipLabel>
    <relationshipName>Project_Competency</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ProjectController.cls
public with sharing class ProjectController {
    public ProjectController() {

    }
    @AuraEnabled(cacheable=true)
    public static List<Company__c> getCompanies(){
        return [select id, Name from Company__c];
    }
    @AuraEnabled(cacheable=true)
    public static List<Competency__c> getCompanyCompetencies(Id companyId){
        return [select id, Name from Competency__c where Company__c =:companyId];
    }
    @AuraEnabled
    public static void createRelatedCompetencies(List<Id> competencies, Id projectId){
        System.debug(competencies);
        System.debug(projectId);
        List<Module__c> Modulelist = new List<Module__c>();
        List<Project_Competency__c> projectCompetencies  = new List<Project_Competency__c>();
        List<Competency__c> companyCompetency = [select id, name from Competency__c where Id in : competencies];
        for(Competency__c compet: companyCompetency){
            projectCompetencies.add(new Project_Competency__c(Project__c = projectId, Name = compet.Name));    
        }
        insert projectCompetencies;
        project__c p = [select id,Start_Date__c,Duration__c from project__c where id =: projectId];
        	Module__c mod = new Module__c();
           	mod.Name = 'Plan & Analysis';
            mod.Start_Date__c = p.Start_Date__c;
           	mod.End_Date__c = p.Start_Date__c.addDays(integer.valueOf(p.Duration__c));
            mod.Projects__c = p.id;    
            Modulelist.add(mod);
            mod = new Module__c();
           	mod.Name = 'Design';
            mod.Start_Date__c = p.Start_Date__c;
            mod.End_Date__c = p.Start_Date__c.addDays(integer.valueOf(p.Duration__c));
            mod.Projects__c = p.id;    
            Modulelist.add(mod);
            mod = new Module__c();
           	mod.Name = 'Iterative Dev';
            mod.Start_Date__c = p.Start_Date__c;
            mod.End_Date__c = p.Start_Date__c.addDays(integer.valueOf(p.Duration__c));
            mod.Projects__c = p.id;    
            Modulelist.add(mod);
            mod = new Module__c();
           	mod.Name = 'Deploy';
            mod.Start_Date__c = p.Start_Date__c;
            mod.End_Date__c = p.Start_Date__c.addDays(integer.valueOf(p.Duration__c));
            mod.Projects__c = p.id;    
            Modulelist.add(mod);
            mod = new Module__c();
           	mod.Name = 'Support';
            mod.Start_Date__c = p.Start_Date__c;
            mod.End_Date__c = p.Start_Date__c.addDays(integer.valueOf(p.Duration__c));
            mod.Projects__c = p.id;    
            Modulelist.add(mod);
        
        if(Modulelist != Null && Modulelist.size() > 0){
        insert Modulelist;
        }
    }
}