force-app/main/default/objects/Company__c/Company__c.object-meta.xml
<CustomObject>
    <label>Company</label>
    <nameField>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Company</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Competency__c/Competency__c.object-meta.xml
<CustomObject>
    <label>Competency</label>
    <nameField>
        <label>Competency Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Competency</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Competency__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <label>Company</label>
    <referenceTo>Company__c</referenceTo>
    <relationshipLabel>Competency</relationshipLabel>
    <relationshipName>Competency</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Module__c/Module__c.object-meta.xml
<CustomObject>
    <label>Module</label>
    <nameField>
        <label>Module Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Modules</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Module__c/fields/Projects__c.field-meta.xml
<CustomField>
    <fullName>Projects__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Modules</relationshipLabel>
    <relationshipName>Modules</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <label>Company</label>
    <referenceTo>Company__c</referenceTo>
    <relationshipLabel>Project</relationshipLabel>
    <relationshipName>Project</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Project_Competency__c/Project_Competency__c.object-meta.xml
<CustomObject>
    <label>Project Competency</label>
    <nameField>
        <label>Competency Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Competency</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Competency__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Project Competency</relationshipLabel>
    <relationshipName>Project_Competency</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Task__c/Task__c.object-meta.xml
<CustomObject>
    <label>Task</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Task_PM__c/Task_PM__c.object-meta.xml
<CustomObject>
    <label>Project Task</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Task_PM__c/fields/GUID__c.field-meta.xml
<CustomField>
    <fullName>GUID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>GUID</label>
    <length>70</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Task_PM__c/fields/Module__c.field-meta.xml
<CustomField>
    <fullName>Module__c</fullName>
    <label>Module</label>
    <referenceTo>Module__c</referenceTo>
    <relationshipLabel>Project Tasks</relationshipLabel>
    <relationshipName>Tasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Team_Member__c/Team_Member__c.object-meta.xml
<CustomObject>
    <label>Team Member</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Team Member</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Team_Member__c/fields/Task__c.field-meta.xml
<CustomField>
    <fullName>Task__c</fullName>
    <label>Task</label>
    <referenceTo>Task_PM__c</referenceTo>
    <relationshipLabel>Team Member</relationshipLabel>
    <relationshipName>Team_Member</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Team_Member__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Team_Member</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/lwcCustomLookupController.cls
public with sharing  class lwcCustomLookupController {
    /*@auraEnabled
    public static list<Account> getResults(string objectName, string fieldName, string value){
        string query = 'select name from '+objectName+ ' where Name =\'%'+fieldName+'%\'';
        List<account> acclist = database.query(query);
        return accList;
    }*/
    final public static String COMPANY_FIELD = 'Company__c';
    final public static String COMPETENCY_FIELD = 'Competency__c';
    @AuraEnabled(cacheable=true)
    public static List<SObJectResult> getResults(String ObjectName, String fieldName, String value, List<String> selectedRecId, String parentId) {
        Set<String> competencies = new Set<String>();
        Set<String> companies = new Set<String>();
        parentid = parentId.substringBefore(':');
        for(Project__c pr :[Select id, 
                        (select Name from Project_Competency__r), 
                        Company__r.Name  
                    From Project__c where id in (select Projects__c from Module__c where id =:parentId)]){
            companies.add(pr.Company__r.Name);
            for(Project_Competency__c pc: pr.Project_Competency__r){
                competencies.add(pc.name);
            }
        }   
        List<SObJectResult> sObjectResultList = new List<SObJectResult>();
        if(selectedRecId == null)
            selectedRecId = new List<String>();

        if(String.isNotEmpty(value)) {
            System.debug(companies);
            System.debug(competencies);
            System.debug(selectedRecId);
            String query = 'Select Id, FirstName, LastName, '+fieldName+' , '+ COMPETENCY_FIELD+' FROM '+ ObjectName+' WHERE '+ fieldName+' LIKE \'%' + value.trim() + '%\' and ID NOT IN: selectedRecId and '+COMPANY_FIELD +' IN: companies and isActive=true';
            System.debug(query);
            sObjectResultList.addAll(PMPublicDataAccess.getUsers(query,selectedRecId, companies, competencies));
        }
        return sObjectResultList;
    }
    
    public class SObjectResult {
        @AuraEnabled
        public String recName;
        @AuraEnabled
        public Id recId;
        
        public SObJectResult(String recNameTemp, Id recIdTemp) {
            recName = recNameTemp;
            recId = recIdTemp;
        }
        public SObJectResult() {
          
        }
    }

    @AuraEnabled(cacheable=true)
    public static void createTaskResources(List<object> resources, Id taskId) {
        for(Object obj: resources){
            System.debug(obj);
            //new Team_Member__c (User__c = obj.recId, Task__c = taskId);
        }
        System.debug('TaskId :'+taskId);

    }
    
    @AuraEnabled
    public static void processResources(Map<String,List<DataWrapper>> resources) {
        Map<String,String> taskGUIDs= new Map<String,String>();
        Set<Team_Member__c> members  = new Set<Team_Member__c>();
        for(Task_PM__c taskPM : [Select id, GUID__c
                                    From Task_PM__c 
                                    Where GUID__c in : resources.keyset()]){
            taskGUIDs.put(taskPM.GUID__c, taskPM.Id);
        }
        
        for(String resourceList:  resources.keyset() ){
            for(DataWrapper res : resources.get(resourceList)){
                members.add(new Team_Member__c(User__c = res.recId,
                                               Task__c = taskGUIDs.get(res.taskGUID)
                                               ));
                System.debug(res);
                system.debug(res.recId);
                system.debug(res.recName);
                system.debug(res.taskGUID);
            }
        }
        System.debug(members.size());
        insert new List<Team_Member__c>(members);
    }
    public class DataWrapper{
        @AuraEnabled
        public String recId {get;set;}
        @AuraEnabled
        public String recName {get;set;}
        @AuraEnabled
        public String taskGUID {get;set;}
    }
}